### PR TITLE
npm: add module

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Comment by teto** [comment]
I don't believe we are meant to create a nix module for every program out there, nor we can.
There must be some motivation for the module, something you wouldn't be able to achieve with just `home.file.".npmrc".text = cfg.npmrc;`

**Comment by rycee** [comment]
I agree with @teto. For example, something like making the settings into an attribute set would be valuable since it would allow merging.

**Comment by offlinehacker** [comment]
Will do

**Comment by offlinehacker** [comment]
I will close this for now

**Pull request closed without merging**
