### PR TITLE
obs-studio: add module

### PR DESCRIPTION
**Pull request by adisbladis**
Preparing for Nixcon :)

### CODE REVIEW

**Comment by rycee** [comment]
Nice! :+1:

I made some changes in 743d7e55a5993091e8db356bd54c1d70bc2e3ffb to be me "HM idiomatic" 🙂If you approve I'll merge with those changes included.

**Comment by rycee** [comment]
(note, I didn't actually test these changes 🙂)

**Comment by adisbladis** [comment]
@rycee Approved!

**Comment by rycee** [comment]
Great! Rebased to master in f44d4a1d8611c8b2f1fce97dc7810722aa10c8cb.

**Pull request closed without merging**
