### PR TITLE
Parametrize path to profile dir

### PR DESCRIPTION
**Pull request by maralorn**
This is a new attempt to solve #280 this time against master.
This seems to work as intended.

But I keep this as Work in progress because I have another unsolved issue (#326), which may be related and leads for me at least to the situation where the changes from this pr work, but do not help.

### CODE REVIEW

**Comment by maralorn** [comment]
As described in #326 I found a way to make this work. You might not like it. This is the best compromise between your suggested solution and my intention, that I got to work.

Also: There is now just one commit (namely 3aac458) which makes the difference between master and nixos-module-user-pkgs. Is there any reason to not merge it into master? I don't see one.

**Comment by rycee** [comment]
Nice! I've rebased this to master in c18b1328a52c0d5ce54924051a43a597b86ff4e3. Note, I simplified the `home.profileDirectory` value to just `cfg.homeDirectory + "/.nix-profile"`. I will change to the richer one for the branch.

**Comment by maralorn** [comment]
That was quick. Nice!

I am just curious. Why even have a specific branch for the nixos-profile? It seems to me that nothing in master would break from merging it. Did I overlook something?

**Comment by rycee** [comment]
I've previously experienced some issues with using the declarative user-package mechanism of NixOS, in particular with programs using the Qt library. My hope is to eventually merge it to master but want to be certain it works well first. And I haven't had time to dig into it properly yet.

**Pull request closed without merging**
