### PR TITLE
Fix xsuspender

### PR DESCRIPTION
**Pull request by fehnomenal**
I wonder how this even worked before.

### CODE REVIEW

**Comment by teto** [comment]
cc the author @offlinehacker . @fehnomenal please rewrite the commit messages as `xsuspender: blabla`

**Comment by romanofski** [comment]
@fehnomenal thanks for doing this. I've just tried out the module myself and ended up with the same patch. Was wondering too.

**Comment by fehnomenal** [comment]
Just reworded the commits

**Comment by rycee** [comment]
Thanks! Rebased to master in 2029e104d45e291cdcc2609893b026362497f4ce.

**Pull request closed without merging**
