### PR TITLE
Automatically start services

### PR DESCRIPTION
**Pull request by nonsequitur**
This patch extends home-manager to manage the running state of services, which enables fully unattended generation switches.

I wrote this right after discovering home-manager, because I use it mainly for declarative service management on non-NixOS systems.
I've been reluctant to share the code because it introduces a new language (Ruby) to the project, and that might pose an unacceptable maintenance burden.
The code is battle-tested and written with an emphasis on clarity — but no offense taken if you downright reject it.

In its current state, this patch is ready to be merged in and to be used immediately with existing home-manager configs — but it's primarily meant as a proposal. If you like the concept, I would suggest some additional changes to add before the release.
(See: `TODO`)

## Synopsis
If the boolean option `systemd.user.startServices` is enabled, the following
happens on systemd activation:

1. Start or restart all services that are wanted by active targets and stop obsolete services from the previous generation.
2. If `systemd.user.servicesStartTimeoutMs > 0` and if any services were (re)started, wait for the specified duration and report services that failed to start. This helps debugging quickly failing services.

Whenever service failures are detected, show the output of `systemd --home status` for the affected services.

## Examples

Start with a simple config:
```bash
cat << 'EOF' > cfg1
{ pkgs, ... }:
{
  systemd.user.startServices = true;

  systemd.user.services.s1 = {
    Service.ExecStart = ''${pkgs.bash}/bin/bash -c "while true; do date; sleep 1; done"'';
    Install.WantedBy = [ "default.target" ];
  };
  systemd.user.services.s2 = {
    Service.ExecStart = ''${pkgs.bash}/bin/bash -c "while true; do echo hi; sleep 1; done"'';
    Install.WantedBy = [ "default.target" ];
  };
}
EOF
home-manager -f cfg1 switch
```

Now switch to another config.
The following happens: Stop old service s1, start new service s3, restart s2 because its config changed,
don't start 'onShutdown' because its target is not active.
```bash
cat << 'EOF' > cfg2
{ pkgs, ... }:
{
  systemd.user.startServices = true;

  systemd.user.services.s2 = {
    Service.ExecStart = ''${pkgs.bash}/bin/bash -c "while true; do echo hello; sleep 1; done"'';
    Install.WantedBy = [ "default.target" ];
  };
  systemd.user.services.s3 = {
    Service.ExecStart = ''${pkgs.bash}/bin/bash -c "while true; do echo foo; sleep 1; done"'';
    Install.WantedBy = [ "default.target" ];
  };
  systemd.user.services.onShutdown = {
    Service.ExecStart = ''${pkgs.bash}/bin/bash -c "echo goodbye"'';
    Install.WantedBy = [ "shutdown.target" ];
  };
}
EOF
home-manager -f cfg2 switch
```

#### Debug helper

Automatically show status for misconfigured services:
```bash
cat << 'EOF' > debugDemo
{ pkgs, ... }:
{
  systemd.user.startServices = true;

  # Error: Relative binary path
  systemd.user.services.s4 = {
    Service.ExecStart = ''bash -c "while true; do echo hello; sleep 1; done"'';
    Install.WantedBy = [ "default.target" ];
  };

  # Error: Relative binary path
  systemd.user.services.s5 = {
    # Error: Invalid option
    Service.Start = ''${pkgs.bash}/bin/bash -c "while true; do echo hello; sleep 1; done"'';
    Install.WantedBy = [ "default.target" ];
  };
}
EOF
home-manager -f debugDemo switch
```

Automatically show status for services that fail soon after starting:
```bash
cat << 'EOF' > failingService
{ pkgs, ... }:
{
  systemd.user.startServices = true;
  systemd.user.servicesStartTimeoutMs = 100;

  systemd.user.services.s6 = {
    Service.ExecStart = ''${pkgs.bash}/bin/bash -c "exit 0"'';
    Install.WantedBy = [ "default.target" ];
  };
}
EOF
home-manager -f failingService switch
```
Stop all
```bash
cat << 'EOF' > stopall
{
  systemd.user.startServices = true;
}
EOF
home-manager -f stopall switch
```

## To do

1. I'd suggest to enable `startServices` by default, maybe at a fixed date.
On this occasion we could then remove the old code that prints suggested commands. We could also port it to the new platform, but I think it's not needed anymore.

2. Add a news item.

### CODE REVIEW

**Comment by rycee** [comment]
Yeah, this is quite neat! The Ruby may or may not be a problem. I'm not sure. I don't have Ruby on my system at the moment so it seems unfortunate to have to install it :-) The alternative would be to use Perl since most Nix(OS) users would have that and the NixOS service starter/stopper is written in it.

I'm a bit short on time at the moment but will ponder this. Thanks again for putting it up!

**Comment by rycee** [comment]
I've looked through this and merged it to master (with an added news entry). I'm still on the fence about whether to move the script to Perl but I don't see any reason not to have this meanwhile.

About switching the default to `true`, I agree but will avoid setting a fixed date just yet.

Many thanks for the PR!

**Comment by nonsequitur** [comment]
Great to hear that!
However long you intend to keep the Ruby version, I'll help maintaining it.

**Comment by rycee** [comment]
Thanks a lot! I sent you a collaborator invite :-)

**Pull request closed without merging**
