### PR TITLE
dbus module: init

### PR DESCRIPTION
**Pull request by gnidorah**
@rycee 
> Ah yeah, that old dbus thing coming back to haunt me again! :angry:

So idea is to switch modules that call dconf, from use of main home-manager systemd service, to user services. Because there is dbus.socket **user** service which propagates DBUS_SESSION_BUS_ADDRESS to other user services. Just compare 
`systemctl status dbus.socket`
and
`systemctl --user status dbus.socket`
Here's details https://serverfault.com/a/906224

### CODE REVIEW

**Comment by rycee** [comment]
Sorry for the delay. I've been traveling a lot and haven't had time to look into this a great deal.

I'm a bit unhappy that something like this would be necessary to have a functioning dconf import. Would it perhaps possible to instead check in the activation script whether a user dbus session is available, run `systemctl --user start dbus.socket` if not, and then run the dconf commands as usual?

**Comment by gnidorah** [comment]
@rycee Oh, I think I've got your idea. Please take a look.

**Comment by rycee** [comment]
Sorry for the delay. I've experimented with and thought about this now and am inclined towards the pure systemd unit solution, I think I was wrong earlier when I insisted on having it directly in the activation script.

I also came to think that we're currently using this module only for setting dconf options and was therefore thinking that maybe it is best to simply have a dconf module. I adapted the code in this PR in a new PR #436 which implements such a dconf module.

One thing I noticed with my tests is that requiring `dbus.socket` doesn't work very well for me, that is why I ended up using `WantedBy = [ "graphical-session-pre.target" ]` since it is reasonably certain that there is a session dbus up and running at that time, see https://github.com/rycee/home-manager/blob/07c6b8521c0ec952745832021c9c87a2476d800e/modules/misc/dconf.nix#L51-L72

**Comment by gnidorah** [comment]
@rycee Cool, thank you! Need to test though, I'm on wayland now (starting sway compositor from console), so not sure whether `graphical-session-pre.target` ever loads in such setup (without display manager)

**Comment by rycee** [comment]
I believe `graphical-session-pre.target` and `graphical-session.target` should be used for Wayland as well. That said, they may at the moment not be used sufficiently generally in Home Manager. Perhaps there should be a `x-graphical-session-pre.target` and `x-graphical-session.target` and `wayland-graphical-session-pre.target` and `wayland-graphical-session.target` for services that are only supporting one or the other?

Oh and just to demonstrate the issue with the `dbus.socket`. On the first run everything goes well, the `DBUS_SESSION_BUS_ADDRESS` value is set to something like `unix:abstract=/tmp/dbus-L2nKDw2gwU,guid=aaa26abd94bb1707c655fa395be08467` which corresponds to the dbus session started by the NixOS xsession script. The requires clause causes `dbus.socket` unit to start (but the service is not triggered because of the above `DBUS_SESSION_BUS_ADDRESS` value), `dbus.socket` does change `DBUS_SESSION_BUS_ADDRESS` to `unix:path=/run/user/1000/bus`, though. So next time you start `dconf-settings.service` it will trigger `dbus.service` and a second dbus user session is started:

```console
$ # Starting dconf-settings.service
$ ps ax | grep dbus
11724 ?        S      0:00 /nix/store/xsgmhmrd6hvjipdsnrn11242q8kmnp2l-dbus-1.12.10-lib/bin/dbus-launch --exit-with-session /nix/store/1nr0clr2czmh6wz4cpb2fzwidx2vwdi1-xsession-wrapper /nix/store/xlczv6n20a2fijz92zj1fkk9r9fqw2l5-xsession "home-manager"
11725 ?        Ss     0:00 /run/current-system/sw/bin/dbus-daemon --syslog --fork --print-pid 5 --print-address 7 --session
$ # Starting dconf-settings.service again
$ ps ax | grep dbus
11724 ?        S      0:00 /nix/store/xsgmhmrd6hvjipdsnrn11242q8kmnp2l-dbus-1.12.10-lib/bin/dbus-launch --exit-with-session /nix/store/1nr0clr2czmh6wz4cpb2fzwidx2vwdi1-xsession-wrapper /nix/store/xlczv6n20a2fijz92zj1fkk9r9fqw2l5-xsession "home-manager"
11725 ?        Ss     0:00 /run/current-system/sw/bin/dbus-daemon --syslog --fork --print-pid 5 --print-address 7 --session
13361 ?        Ss     0:00 /nix/store/kxxc8m9pzqv71hpzp9sk246h4b9xbhvj-dbus-1.12.10/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
```

**Comment by gnidorah** [comment]
@rycee In case of pure wayland setup there is nothing that starts `graphical-session.target`, no display manager is used. Person just starts compositor manually from console. systemd is not involved.

**Pull request closed without merging**
