### PR TITLE
i3: support for bar tray_output option

### PR DESCRIPTION
**Pull request by dsx**

### CODE REVIEW

**Comment by kalbasit** [comment]
@rycee should he file a separate PR here? IMO changes are related and one commit per each change so just edit the title of the PR.

**Comment by dsx** [comment]
I'll push new PR. GitHub is confusing :)

**Comment by rycee** [comment]
I certainly don't mind multiple related smaller commits in a single PR, it is quite convenient that way :-)

**Comment by rycee** [comment]
Thanks for the contribution! Rebased to master in 71f6bc41eb408f1ee53a128d24feffb18248f6fc.

I noticed that the PR uses `types.string` but it almost certainly should be `types.str`. But then I also noticed that the whole module uses `types.string`, which I think should be fixed en masse in a separate PR.

**Pull request closed without merging**
