### PR TITLE
fonts: add module

### PR DESCRIPTION
**Pull request by rycee**
@Mic92, @uvNikita: If you have the time and will then please have a quick look at this. It implements the suggestion I made in #87.

### CODE REVIEW

**Comment by uvNikita** [comment]
I don't quite understand, why NixOs users should not use this parameter. I've just moved all my fonts from system configuration to `home.packages` and I don't have `$HOME/.local/share/fonts` directory. Am I missing something?

**Comment by Mic92** [comment]
fontsconfig from nixpkgs already looks for fonts in `~/.nix-profile/share/fonts` so this is mainly useful for non-nixpkgs on non-nixos systems.

**Comment by rycee** [comment]
Indeed, that is the reason.

Btw, I just had the idea that fontconfig might know about per-user configuration dirs and indeed [it seems to do so](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html). So my idea now is to rework this PR to not create a `~/.local/share/fonts` but rather a `~/.config/fontconfig/conf.d/nix-fonts.conf` file that tells the user's fontconfig about the `~/.nix-profile/share/fonts` directory…

**Comment by rycee** [comment]
Changed the commit to implement the fontconfig configuration…

**Pull request merged**
