### PR TITLE
Allow specifying starship package.

### PR DESCRIPTION
**Pull request by davidtwco**

### CODE REVIEW

**Comment by rycee** [comment]
Hmm, the preferred way to override packages would be to add an overlay. E.g., along the lines of
```
nixpkgs.overlays = [
  (self: super: {
    starship = …;
  })
];
```
I'm OK with having a package option if there is a strong argument for it, though.

**Comment by davidtwco** [comment]
I've found that it's quite easy to get Nix stuck until it consumes all your memory when creating an overlay that overrides a package (particularly when I override from the `unstable` channel I have pinned) - that's almost certainly me doing something wrong, but it's hard to go wrong with a package option, it's more intuitive and discoverable, IMO.

**Comment by shanesveller** [comment]
There are other examples within `home-manager` that offer this approach too, such as `programs.emacs.package`. I've wound up using the overlay approach in the meantime, so I can pull `starship` in particular from `nixpkgs-unstable` channel.

**Comment by rycee** [comment]
Fair enough! Rebased to master in 5c9ec0d8e9bb2b358ee5cb57742fc5f55802dde2.

**Pull request closed without merging**
