### PR TITLE
kanshi: fix exec configuration

### PR DESCRIPTION
**Pull request by berbiche**
### Description

Kanshi's generated configuration does not work for the `exec` option.

I also tested the changes with my configuration (the kanshi service would not start previously).

### Checklist

- [ ] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/rycee/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by berbiche** [comment]
cc @nurelin

**Comment by nurelin** [comment]
Silly of me to have overlooked this.
Is it necessary to add a new test case instead of adding the missing exec in the existing one ?
Otherwise, looks good to me.

**Review by nurelin — COMMENTED** [review]
Is it necessary to add a new test case instead of adding the missing exec in the existing one ?

**Comment by berbiche** [comment]
> Is it necessary to add a new test case instead of adding the missing exec in the existing one ?

Done

**Review by nurelin — APPROVED** [review]

**Comment by berbiche** [comment]
@rycee This is an easy fix and merge, if you have time 😄

**Comment by rycee** [comment]
Thanks! Rebased to master in 182454fe6b2342011ac3ae7c93cf5fb0ccd17bd7.

**Pull request closed without merging**
