### PR TITLE
Tmux

### PR DESCRIPTION
**Pull request by rycee**

### CODE REVIEW

**Comment by srid** [comment]
@stites @rycee - What is the benefit of using this module over `programs.tmux` in nixpkgs ([which I currently use](https://github.com/srid/mynixos/blob/16d8009/nix/tmux.nix))?

**Comment by rycee** [comment]
@srid Well, I guess the major difference is that the one in Home Manager is per-user while the NixOS one is system wide.

The other differences, from what I can tell, are that the NixOS one does not provide tmux plugin management while the HM one at the moment does not provide detailed options such as `historyLimit`, `keyMode`, etc.

I don't use tmux so I can't say which one is best to use, I think it will depend on your needs.

**Comment by stites** [comment]
The primary motivator was replacing [tpm](https://github.com/tmux-plugins/tpm) with nix. Looking at the options available. It's unclear to me if a nixpkg user can access these configurations in nixos modules.

That said, I didn't even realize there were these sorts of options were available -- is it possible to configure packages like this if you are on, say, arch or ubuntu?.

**Comment by srid** [comment]
Is it not possible to extend the original nixpkgs module, and re-use it in home-manager? For the benefit of having a single source of truth, as it were.

**Comment by rycee** [comment]
@srid Unfortunately no, there is no easy way to share module implementations between projects. I have attempted it a few times but it's always lead to difficulties. I believe there should be a way to do it but right now I'm not certain what the solution might be.

**Comment by stites** [comment]
I wholeheartedly agree! Since it seems like home-manager is easier to deploy remotely and runs on non-nixos boxes, I'm of the opinion that everything should be migrated here. That said, I won't have time to work on this until the holidays -- if someone else wants to take a crack at this, please do so!

**Pull request merged**
