### PR TITLE
i3: add missing bar options

### LINKED ISSUE #210: i3 add extraConfig for bars
I was looking at converting my i3 bar config to home-manager's format but I miss some options, it would be nice to have a per bar extraConfig. Here are some options I miss
 ```
	strip_workspace_numbers 1
	id 0
	# -t => transparent, available only in i3gaps
	# i3bar_command i3bar -t
	i3bar_command i3bar
    colors {
        background $bar_bg
        statusline $bar_status
        # class            border  backgrd text
        focused_workspace  $foc_border $foc_border_bg #FFFF50
        active_workspace   #06090d #06090d #696f89
        inactive_workspace #06090d #06090d #696f89
        urgent_workspace   #d72f6b #d70a53 #FFFF50
		binding_mode       #rrrrrr #rrffrr #ffffff
    }

```

### PR DESCRIPTION
**Pull request by uvNikita**
New options are: id, commmand, workspaceNumbers, colors.
Fixes #210.

### CODE REVIEW

**Comment by teto** [comment]
Looks good to me. Tested id/workspaceNumber locally and it worked fine

**Comment by uvNikita** [comment]
Merged into master: https://github.com/rycee/home-manager/commit/de001e05da3f9456d658aabe62f1cc2fa663cbb0. @teto thanks for creating the issue and testing.

**Comment by jwiegley** [comment]
@uvNikita This breaks darwin because of the following reference made in an example:

```
command = mkOption {
  type = types.string;
  default = "${cfg.package}/bin/i3bar";
  defaultText = "i3bar";
  description = "Command that will be used to start a bar.";
  example = "${pkgs.i3-gaps}/bin/i3bar -t";
};
```

The reference to `${pkgs.i3-gaps}` causes home-manager to build this derivation, even though I have no interest in using i3. But since i3 cannot build on Darwin, home-manager can't build at all.

**Comment by teto** [comment]
Found it. I'll fix it, I just need to wait for the current build to finish.

**Comment by uvNikita** [comment]
@jwiegley, thanks for pointing this out!
@teto yes, I think `example = literalExample "{pkgs.i3...}"` should do the trick.

**Comment by teto** [comment]
@jwiegley please test master, I couldn't test it but it should be ok.

**Comment by jwiegley** [comment]
@uvNikita Thanks for the quick work, but I'm still seeing the same error:

```
$ home-manager switch
error: assertion failed at /Users/johnw/src/nix/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:120:36
(use '--show-trace' to show detailed location information)

$ git branch -v
  bash-history 1229124 Add option programs.bash.historyFile
* master       6d7b5c9 i3: don't evaluate "command" example
  ssh-options  3012184 Add a few more options to the ssh module
```

**Comment by uvNikita** [comment]
I'm not 100% sure, but I guess it could be due to `home-manager` binary been broken for you already. Could you please try to follow [this](https://github.com/rycee/home-manager#rollbacks) steps to rollback to the version that was working for you, and then try to update to the latest master?

**Comment by dustinlacewell-wk** [comment]
I don't understand, was this PR merged?

**Comment by jwiegley** [comment]
@uvNikita Still same error:

```
╭─ johnw@Vulcan  ~/src/nix/home-manager   master ⍟1                              ✔  10:05:51
╰─ /nix/store/lgmx4l88kwwc7bw171f7xpq7snqmv7jy-home-manager-generation/activate
Starting home manager activation
Activating checkLinkTargets
Activating writeBoundary
Activating uninstallHomeManager
Activating installPackages
replacing old ‘home-manager-path’
installing ‘home-manager-path’
Activating linkGeneration
Cleaning up orphan links from /Users/johnw
No change so reusing latest profile generation 165
Creating home file links in /Users/johnw
╭─ johnw@Vulcan  ~/src/nix/home-manager   master ⍟1                              ✔  10:06:03
╰─ home
home-manager switch
error: assertion failed at /Users/johnw/src/nix/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:120:36
(use '--show-trace' to show detailed location information)
make: *** [Makefile:12: home-switch] Error 1
```

**Comment by jwiegley** [comment]
Note that I've garbage collected, so the only generation of home-manager available is the result of using `home-manager activate` after rolling back to `master~2`.

**Comment by uvNikita** [comment]
I think I finally figured out the right way to escape `${}` evaluation. @jwiegley could you please try to switch to the latest master and see if it works? Sorry everyone for the inconvenience.

**Comment by rycee** [comment]
Glad the issues got sorted out! Many thanks for the quick report @jwiegley and thanks to @teto and @uvNikita for working to fix the problem.

To help avoid similar hiccups in the future I looked into Travis-CI and managed to create a small setup that attempts to do a minimal install on both Linux and macOS: #216

**Comment by jwiegley** [comment]
@uvNikita Yes, it's working for me now, thanks!

**Pull request closed without merging**
