### PR TITLE
Fix path to profile dir when using as nixos submodule

### PR DESCRIPTION
**Pull request by maralorn**
The normal session-variable management with 
```
. "$HOME/.nix-profile/etc/profile.de/hm-session-vars.sh"
```
does not work when using the nixos-module. I have fixed all occasions of `~/.nix-profile` i found by using `grep`.

I don't know, if this is the best way. I would actually prefer just replacing `$HOME/.nix-profile` with `${config.home.path}` everywhere. Don't know if that would break anything.

### CODE REVIEW

**Comment by rycee** [comment]
Ah, I was just thinking of this problem! Thanks for taking the time to fix! I will have trouble looking through this thoroughly before Sunday so please be patient 😃

On May 31, 2018 9:08:26 PM GMT+02:00, Malte Brandy <notifications@github.com> wrote:
>The normal session-variable management with 
>```
>. "$HOME/.nix-profile/etc/profile.de/hm-session-vars.sh"
>```
>does not work when using the nixos-module. I have fixed all occasions
>of `~/.nix-profile` i found by using `grep`.
>
>I don't know, if this is the best way. I would actually prefer just
>replacing ${profileDir} with ${config.home.path} everywhere. Don't know
>if that would break anything.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/rycee/home-manager/pull/280
>
>-- Commit Summary --
>
>  * Fix path to profile dir when using as nixos submodule
>
>-- File Changes --
>
>    M modules/programs/bash.nix (4)
>    M modules/programs/info.nix (4)
>    M modules/programs/zsh.nix (4)
>    M modules/services/dunst.nix (2)
>    M modules/services/flameshot.nix (3)
>    M modules/services/owncloud-client.nix (8)
>    M modules/services/syncthing.nix (7)
>    M modules/xsession.nix (3)
>
>-- Patch Links --
>
>https://github.com/rycee/home-manager/pull/280.patch
>https://github.com/rycee/home-manager/pull/280.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rycee/home-manager/pull/280

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rycee** [comment]
Had a look and I'm thinking that it is best to avoid using `config.home.path` because it might cause issues in some cases if you also install programs yourself (i.e., not through `home.packages`).

I'm also thinking one could abstract away the profile directory variable into an option, something like

```patch
diff --git a/modules/home-environment.nix b/modules/home-environment.nix
index 8e896de..4a17ab7 100644
--- a/modules/home-environment.nix
+++ b/modules/home-environment.nix
@@ -121,6 +121,17 @@ in
       description = "The user's home directory.";
     };
 
+    home.profileDirectory = mkOption {
+      type = types.path;
+      defaultText = "~/.nix-profile";
+      internal = true;
+      readOnly = true;
+      description = ''
+        The profile directory where Home Manager generations are
+        installed.
+      '';
+    };
+
     home.language = mkOption {
       type = languageSubModule;
       default = {};
@@ -248,6 +259,8 @@ in
 
     home.username = mkDefault (builtins.getEnv "USER");
     home.homeDirectory = mkDefault (builtins.getEnv "HOME");
+    home.profileDirectory = mkIf (!config.nixosSubmodule) (
+      mkDefault (cfg.homeDirectory + "/.nix-profile"));
 
     home.sessionVariables =
       let
diff --git a/modules/misc/fontconfig.nix b/modules/misc/fontconfig.nix
index 5723cf8..a275f56 100644
--- a/modules/misc/fontconfig.nix
+++ b/modules/misc/fontconfig.nix
@@ -50,8 +50,8 @@ in
         <?xml version='1.0'?>
         <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
         <fontconfig>
-          <dir>/etc/profiles/per-user/${config.home.username}/lib/X11/fonts</dir>
-          <dir>/etc/profiles/per-user/${config.home.username}/share/fonts</dir>
+          <dir>${config.home.profileDirectory}/lib/X11/fonts</dir>
+          <dir>${config.home.profileDirectory}/share/fonts</dir>
         </fontconfig>
       '';
     })
diff --git a/modules/services/syncthing.nix b/modules/services/syncthing.nix
index 1151172..7fc556c 100644
--- a/modules/services/syncthing.nix
+++ b/modules/services/syncthing.nix
@@ -54,7 +54,7 @@ with lib;
           };
 
           Service = {
-            Environment = "PATH=%h/.nix-profile/bin";
+            Environment = "PATH=${config.home.profileDirectory}/bin";
             ExecStart = "${pkgs.qsyncthingtray}/bin/QSyncthingTray";
           };
 
diff --git a/nixos/default.nix b/nixos/default.nix
index ae7a5ef..a84f2f2 100644
--- a/nixos/default.nix
+++ b/nixos/default.nix
@@ -15,6 +15,7 @@ let
     config = {
       home.username = config.users.users.${name}.name;
       home.homeDirectory = config.users.users.${name}.home;
+      home.profileDirectory = "/etc/profiles/per-user/${config.home.username}";
     };
   });
```
(Note, the above is not thoroughly tested)

**Comment by rycee** [comment]
Note, ideally the change is made in master first and then ported to this branch (which hopefully can make it into master someday).

**Comment by maralorn** [comment]
I opened a new branch with a new pr.

**Pull request closed without merging**
