### PR TITLE
termite: use vte-ng at pkgs.termite.vte-ng

### LINKED ISSUE #864: attribute 'vte-ng' missing, at home-manager/modules/programs/termite.nix
vte-ng got removed from nixpkgs upstream in https://github.com/NixOS/nixpkgs/commit/b8ab8598ed3f6d2efefc08fe908a6cce49c38974

I'm going to file a PR upstream to expose vte-ng by termite.

### PR DESCRIPTION
**Pull request by kalbasit**
depends on https://github.com/NixOS/nixpkgs/pull/70776
closes #864

### CODE REVIEW

**Comment by rycee** [comment]
Thanks for the contribution. I've sent you a contributor invite so that you can merge this your self when it's ready. Please have a look at the [contribution guidelines](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md) if you haven't already and please keep opening PRs for non-trivial changes :+1:

**Comment by kalbasit** [comment]
@rycee I merged the PR upstream. With this change, master would require nixpkgs to have the commit https://github.com/NixOS/nixpkgs/commit/9dc7b25eaad9db50cd48b2e17215969e78aa0e32. How do you want to handle this? Should I piggyback off of `config.home.stateVersion`?

**Comment by rycee** [comment]
I understand that the old code no longer works with master Nixpkgs. If so then I would suggest simply merging this PR once you fix in Nixpkgs has been introduced in the unstable channel. Well, if it doesn't work you can just merge right now since it wouldn't make the situation worse 🙂

**Comment by juripaern0007** [comment]
@kalbasit I'm affected by this. I updated today my nix-channel today  but I still have this issue
`system and user nix-channel --update && home-manager switch`.

What do I need to do, to be able to do a successful `home-manager switch`?

**Comment by kalbasit** [comment]
> @kalbasit I'm affected by this. I updated today my nix-channel today but I still have this issue
> `system and user nix-channel --update && home-manager switch`.
> 
> What do I need to do, to be able to do a successful `home-manager switch`?

What NixOS channel are you on? If you're using 19.09 then you should use the 19.09 branch of home-manager to get this work.

**Pull request merged**
