### PR TITLE
fish: fix fish plugins complete path update

### PR DESCRIPTION
**Pull request by terlar**
### Description

Currently when installing plugins with completions it will update the completion and due to a type pop the first item and then add the function path into there. Resulting in functions being loaded as completions and also the first item in the completion list being lost.

### Checklist

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [x] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md#commits) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/rycee/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

  - [ ] Added myself and the module files to `.github/CODEOWNERS`.

### CODE REVIEW

**Comment by terlar** [comment]
BTW, I still have issues running the test suite locally:
```
$ nix-shell --pure tests -A run.all
trace: warning: In file /home/terje.larsen/src/github.com/rycee/home-manager/tests/lib/types/list-or-dag-merge.nix
a list is being assigned to the option 'tested.dag'.
This will soon be an error due to the list form being deprecated.
Please use the attribute set form instead with DAG functions to
express the desired order of entries.

trace: warning: In file /home/terje.larsen/src/github.com/rycee/home-manager/tests/lib/types/list-or-dag-merge.nix
a list is being assigned to the option 'tested.dag'.
This will soon be an error due to the list form being deprecated.
Please use the attribute set form instead with DAG functions to
express the desired order of entries.

abook-no-settings: OK
abook-with-settings: OK
alacritty-empty-settings: OK
alacritty-example-settings: OK
bash-logout: OK
bash-session-variables: OK
browserpass: OK
debug: OK
files-executable: OK
files-hidden-source: OK
files-source-with-spaces: OK
files-text: OK
firefox-profile-settings: OK
firefox-state-version-19_09: OK
fish-functions: OK
fish-no-functions: OK
fish-plugins: OK
fontconfig-multiple-font-packages: OK
fontconfig-no-font-package: OK
fontconfig-single-font-package: OK
getmail: OK
git-with-email: OK
git-with-most-options: OK
git-with-str-extra-config: OK
gpg-override-defaults: OK
home-session-variables: OK
i3-keybindings: OK
kakoune-whitespace-highlighter: OK
lib-types-dag-merge: OK
lib-types-dag-submodule: OK
lib-types-gvariant-merge: OK
lib-types-list-or-dag-merge: OK
lieer: OK
lieer-service: FAILED
Expected home-files/.config/systemd/user/lieer-hm-example-com.service to exist but it was not found.
For further reference please introspect /nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service
mbsync: OK
neomutt-simple: OK
neomutt-with-msmtp: OK
newsboat-basics: OK
newsboat-basics-2003: OK
pam-session-variables: OK
polybar-basic-configuration: OK
qutebrowser-settings: OK
readline-using-all-options: OK
rofi-assert-on-both-theme-and-colors: OK
ssh-defaults: OK
ssh-forwards-dynamic-bind-path-with-port-asserts: OK
ssh-forwards-dynamic-valid-bind-no-asserts: OK
ssh-forwards-local-bind-path-with-port-asserts: OK
ssh-forwards-local-host-path-with-port-asserts: OK
ssh-forwards-remote-bind-path-with-port-asserts: OK
ssh-forwards-remote-host-path-with-port-asserts: OK
ssh-match-blocks: OK
starship-settings: OK
sxhkd-configuration: OK
sxhkd-service: OK
systemd-services: OK
systemd-session-variables: OK
systemd-timers: OK
targets-generic-linux: OK
texlive-minimal: OK
tmux-disable-confirmation-prompt: OK
tmux-emacs-with-plugins: OK
tmux-not-enabled: OK
tmux-secure-socket-enabled: OK
tmux-vi-all-true: OK
xdg-mime-apps-basics: OK
xresources: OK
xsession-basic: FAILED
Expected home-files/.config/systemd/user/setxkbmap.service to exist but it was not found.
For further reference please introspect /nix/store/r6xsrp7zi09m4nwvrn65f73k4gcw0cim-nmt-report-xsession-basic
xsession-keyboard-without-layout: FAILED
Expected home-files/.config/systemd/user/setxkbmap.service to exist but it was not found.
For further reference please introspect /nix/store/ajnl6a7sc72ynd4ssahymwzn6d7r7dfi-nmt-report-xsession-keyboard-without-layout
zsh-history-path-new-custom: OK
zsh-history-path-new-default: OK
zsh-history-path-old-custom: OK
zsh-history-path-old-default: OK
zsh-session-variables: OK
```

It is always those same tests that fail.

System info (running a git checkout of latest nixos-unstable b61999e4ad6):
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.16, NixOS, 20.09.git.b61999e4ad6 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-18.09.2574.a7e559a5504"`
 - channels(terje.larsen): `""`
 - nixpkgs: `/home/terje.larsen/src/github.com/terlar/nix-config/external/nixpkgs`

**Comment by rycee** [comment]
Thanks! Rebased to master in 9905ab508792517bb8c2991f2b82873dc7d5cd8b.

I'm not sure why some people seem to get these test failures. I've been unable to reproduce them, o matter which version of Nix or Nixpkgs I use 😕

**Comment by rycee** [comment]
Could you see what
```
$ find -L /nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files
```
says?

**Comment by terlar** [comment]
@rycee Yes, I understand that, that is why I would like to assist, since I can't find a way not to reproduce it. Should I create another issue for this?

```
$ find -L /nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.config
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.config/systemd
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.config/systemd/user
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.config/systemd/user/lieer-hm-example-com.service
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.config/systemd/user/timers.target.wants
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.config/systemd/user/timers.target.wants/lieer-hm-example-com.timer
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.config/systemd/user/lieer-hm-example-com.timer
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.cache
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/home/terje.larsen/.cache/.keep
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/Mail
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/Mail/hm@example.com
/nix/store/pklzzh2qr48iplaav7ddf1jnkj03kr4c-nmt-report-lieer-service/tested/home-files/Mail/hm@example.com/.gmailieer.json
```

**Comment by terlar** [comment]
So looking at this, is that the case, it is looking for:
`home-files/.config/systemd/user/lieer-hm-example-com.service`
but in my case it is:
`/home-files/home/terje.larsen/.config/systemd/user/lieer-hm-example-com.service`

**Pull request closed without merging**
