### PR TITLE
Add section "Add relevant documentation" to contributing guidelines in the manual

### PR DESCRIPTION
**Pull request by DamienCassou**
### Description

- adds a section "Add relevant documentation" to contributing guidelines in the manual. This should help the contributor check changes to the documentation
- adds "html-manual" and "manPages" attributes to default.nix.

### Checklist

- [x] Change is backwards compatible.
- [x] Code formatted with `./format`.
- [x] Commit messages are formatted like

### CODE REVIEW

**Comment by Kloenk** [comment]
Are those the docs build with nmd? Maybe we could use this to fix the usage of nmd? (it breaks hydra and some evaluators because of import-from-derivation)

**Comment by DamienCassou** [comment]
> Are those the docs build with nmd?

I think so

> Maybe we could use this to fix the usage of nmd?

I don't know what you are talking about. Is there anything I should do?

**Comment by Kloenk** [comment]
> > Maybe we could use this to fix the usage of nmd?
> 
> I don't know what you are talking about. Is there anything I should do?

I had to deactivate the `home-manager` docs in my system, because I'm unable to evaluate my systems if I have them enabled. The problem is with `import-from-derivation`, where I'm unable to see how many builds I'm doing at the end (hydra breaks).

**Comment by DamienCassou** [comment]
What is the relation between what you are talking about and what I did?

**Comment by rycee** [comment]
Thanks, I think this was a really good idea! I've made some minor edits and rebased to master in 4ba9cedd686a068c2628029e1fafa1f049594b53.

**Pull request closed without merging**
