### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BjornMelgaard**
resolves https://github.com/rycee/home-manager/issues/116

### CODE REVIEW

**Comment by rycee** [comment]
Good point, I think this should be in the README file. But I'd like for the description to be somewhat more general and be sensible also for users who don't run NixOS. I'd suggest something like the following change:

```patch
diff --git a/README.md b/README.md
index 0ad9fc6..339d715 100644
--- a/README.md
+++ b/README.md
@@ -46,6 +46,14 @@ Currently the easiest way to install Home Manager is as follows:
     since Home Manager uses these directories to manage your profile
     generations. On NixOS these should already be available.
 
+    Also make sure that your user is able to build and install Nix
+    packages. For example, you should be able to successfully run a
+    command like `nix-instantiate '<nixpkgs>' -A hello`. For a
+    multi-user install of Nix this means that your user must be
+    covered by the [`allowed-users`][nixAllowedUsers] Nix option. On
+    NixOS you can control this option using the
+    [`nix.allowedUsers`][nixosAllowedUsers] system option.
+
 2.  Assign a temporary variable holding the URL to the appropriate
     archive. Typically this is
 
@@ -71,12 +79,7 @@ Currently the easiest way to install Home Manager is as follows:
     }
     EOF
     ```
-3.  Add yourself to `nix.trustedUsers`:
-    For example if you in `@wheel` group, insert this to your 
-    `configuration.nix` 
-    ```
-    nix.trustedUsers = [ "root" "@wheel" ];
-    ```
+
 3.  Create the first Home Manager generation:
 
     ```console
@@ -240,3 +243,5 @@ in your Home Manager configuration.
 [Nix]: https://nixos.org/nix/
 [NixOS]: https://nixos.org/
 [Nixpkgs]: https://nixos.org/nixpkgs/
+[nixAllowedUsers]: https://nixos.org/nix/manual/#conf-allowed-users
+[nixosAllowedUsers]: https://nixos.org/nixos/manual/options.html#opt-nix.allowedUsers
```

**Comment by BjornMelgaard** [comment]
@rycee 
but error was due to I was not in `trustedUsers`, and not in `allowedUsers`, `allowedUsers` was default value - '*'
```
 ✘  ~/.config/dotfiles   nixos ●  cat /etc/nix/nix.conf
# WARNING: this file is generated from the nix.* options in
# your NixOS configuration, typically
# /etc/nixos/configuration.nix.  Do not edit it!
build-users-group = nixbld
build-max-jobs = 4
build-cores = 1
build-use-sandbox = false
build-sandbox-paths =  /bin/sh=/nix/store/qp5fw57d38bd1n07ss4zxh88zg67c3vg-bash-4.4-p12/bin/bash /nix/store/qp5fw57d38bd1n07ss4zxh88zg67c3vg-bash-4.4-p12 /nix/store/xzx1bv1d7z4mgg6sg6ly0jx609qvka4x-glibc-2.25-49
binary-caches = https://cache.nixos.org/
trusted-binary-caches =
binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
auto-optimise-store = false
signed-binary-caches = *

trusted-users = root @wheel
allowed-users = *
```

**Comment by rycee** [comment]
Hmm, I think it must be something else. I have
```console
rycee@beta:~$ grep users /etc/nix/nix.conf 
build-users-group = nixbld
trusted-users = root
allowed-users = *
rycee@beta:~$ groups
users wheel cdrom video networkmanager systemd-journal vboxusers wireshark
```
and it definitely works for me. I think my builds happen in `/tmp` though, perhaps you have some other setting going on somewhere?

**Comment by BjornMelgaard** [comment]
Even can't imagine what can affect to this

This is my [configuration.nix ](https://github.com/BjornMelgaard/dotfiles/blob/master/nixos/root/default.nix)

**Comment by BjornMelgaard** [comment]
now I have different issue: files created through `text` are working, but not through `source`
For example if I uncomment [this line](https://github.com/BjornMelgaard/dotfiles/blob/master/nixos/home/default.nix#L31) and run

```sh
 ~/.config/dotfiles   master  home-manager switch
these derivations will be built:
  /nix/store/lq2j6qhl8623zydw35a5hwcrns3s4yk2-home-manager-files.drv
  /nix/store/4pv5ira1ln8yq7vgkwm6mc5gaa5zji08-home-manager-generation.drv
building path(s) ‘/nix/store/1hyx2h5qzhqlr06sdjagadisbggfbrjg-home-manager-files’
installing
install: cannot stat '/home/bjorn/.config/dotfiles/zshrc': Permission denied
builder for ‘/nix/store/lq2j6qhl8623zydw35a5hwcrns3s4yk2-home-manager-files.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/4pv5ira1ln8yq7vgkwm6mc5gaa5zji08-home-manager-generation.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/4pv5ira1ln8yq7vgkwm6mc5gaa5zji08-home-manager-generation.drv’ failed
```

Permissions of dotfiles
```
 ✘  ~/.config/dotfiles   master ●  la
total 116K
drwxr-xr-x 2 bjorn users 4.0K Nov  5 17:46 bin/
-rwxr-xr-x 1 bjorn users 1.1K Nov  5 17:46 commitlintrc.yml*
-rw-r--r-- 1 bjorn users 2.0K Oct 30 00:08 ctags
-rw-r--r-- 1 bjorn users  815 Oct 30 00:08 cvimrc
-rwxr-xr-x 1 bjorn users 6.5K Nov  5 17:46 dunstrc*
drwxr-xr-x 9 bjorn users 4.0K Nov  5 17:54 .git/
-rw-r--r-- 1 bjorn users  865 Oct 30 00:08 gitconfig
-rw-r--r-- 1 bjorn users  197 Oct 30 00:08 .gitignore
-rw-r--r-- 1 bjorn users   27 Oct 30 00:08 gitignore_global
-rw-r--r-- 1 bjorn users  577 Nov  5 17:46 .gitmodules
-rw-r--r-- 1 bjorn users  532 Nov  5 17:46 gtk-3.0-settings.ini
-rw-r--r-- 1 bjorn users  627 Nov  5 17:46 gtkrc-2.0
drwxr-xr-x 3 bjorn users 4.0K Nov  5 17:46 i3/
-rwxr-xr-x 1 bjorn users 1.3K Nov  5 17:46 install.rb*
drwxr-xr-x 2 bjorn users 4.0K Oct 30 00:08 layouts/
-rw-r--r-- 1 bjorn users  619 Oct 30 00:08 ncmpcpp_bindings
drwxr-xr-x 4 bjorn users 4.0K Nov  5 17:46 nixos/
drwxr-xr-x 8 bjorn users 4.0K Nov  5 17:46 nvim/
drwxr-xr-x 3 bjorn users 4.0K Oct 30 00:08 oh-my-zsh/
drwxr-xr-x 2 bjorn users 4.0K Nov  5 17:34 ranger/
-rw-r--r-- 1 bjorn users  602 Oct 30 00:08 stack-global.yaml
drwxr-xr-x 2 bjorn users 4.0K Oct 30 00:08 termite/
drwxr-xr-x 4 bjorn users 4.0K Nov  5 13:12 tmux/
-rw-r--r-- 1 bjorn users 2.0K Nov  5 17:46 tmux.conf
drwxr-xr-x 7 bjorn users 4.0K Nov  5 17:46 .trash/
drwxr-xr-x 2 bjorn users 4.0K Nov  5 17:46 Xresources/
drwxr-xr-x 3 bjorn users 4.0K Nov  5 17:46 zsh/
-rw-r--r-- 1 bjorn users 1.2K Nov  5 17:46 zshrc
```

`~/.config` - `drwxr-xr-x`
`~/.config/dotfiles` - `drwxr--r--`

**Comment by rycee** [comment]
I guess the nix-daemon user cannot access the files in `~/.config/dotfiles` because of the permissions `drwxr--r--`, I think it'll need `x` rights.

By the way, paths given as `source` should be of Nix type "path", if it is a string (like "/home/bjorn/...") then you typically run into problems where Nix cannot find the file due to it being outside the build sandbox. Try changing

    dotfilesDir="/home/bjorn/.config/dotfiles";

to

    dotfilesDir=/home/bjorn/.config/dotfiles;

I suspect you need to do `builtins.toString dotfilesDir` in some places afterwards, e.g., in `export PATH="$PATH:${dotfilesDir}/bin"`.

**Comment by rycee** [comment]
About the

> error: creating symlink from ‘/etc/nixos/result.tmp-27440-1730106898’ to ‘/nix/store/ci9j6ms78lyklicjq8b6i5n3z4xh85ll-home-manager-generation’: Permission denied

error. It seems to be caused by running home-manager while your current working directory was /etc/nixos. For some reason `nix-build` generates this file in the current directory. I'll try to figure out a way for it not to do that. But for now, please run home-manager in a directory where you have rw access.

**Comment by BjornMelgaard** [comment]
@rycee fk, yes, I feel dumb))
All was as you said: executable `dotfiles` (forgot about this), dotfilesDir as path (did not even need
to use `toString`), `home-manager switch` in `/etc`

Thanks)

I'll change pr and you can merge then)

**Comment by BjornMelgaard** [comment]
done

**Comment by rycee** [comment]
Rebased this to master in fc3e82584bda579739f01b57e5f31adea2bce593. Note, I changed the commit message slightly to better match the contribution guidelines.

Many thanks for your help!

**Pull request closed without merging**
