### PR TITLE
Fix mpdris2 service so it may start automatically

### PR DESCRIPTION
**Pull request by leotaku**
The mpdris2 service doesn't currently seem to start, as it isn't WantedBy anything.

This PR fixes said issue.

### CODE REVIEW

**Comment by leotaku** [comment]
I'm not sure if it makes sense for this service to only start after the `graphical-session.target`. I don't see why it would, but if it does (maybe because of some dbus shenanigans) I'll re-add that `After`.

**Comment by rycee** [comment]
I'm guessing the systemd service is not really used and instead mpdris2 is activated by dbus. The user dbus session in NixOS is activated with the X session and does not communicate with systemd so from systemd's point of view it's not running. I don't know if it is possible to correctly have both a systemd service and a dbus one under NixOS, won't you end up with two running instances of mpdris2?

**Comment by leotaku** [comment]
@rycee Well I just know that I was only able to get the mpdris2 functionality to work by either manually starting the service, or using the changes proposed in this PR.

> The user dbus session in NixOS is activated with the X session and does not communicate with systemd so from systemd's point of view it's not running.

I don't really know much about the intricacies of dbus, but if it works separately from the user systemd session, why would this module even define an user systemd service? I was always under the impression that dbus's service functionality was tightly coupled with systemd.

**Comment by rycee** [comment]
I'm not sure why it is there, perhaps @pjones knows? I think these changes should be fine, though. The only thing I can think of is changing the service to include `BusName=org.mpris.MediaPlayer2.mpd` like in the [upstream service file](https://github.com/eonpatapon/mpDris2/blob/69c4426624647928db1c04675a81a1d02813908e/src/mpDris2.service.in).

About the dbus/systemd issue I mentioned have a look at https://github.com/NixOS/nixpkgs/issues/17943#issuecomment-341860410 for a description I wrote a while back.

**Comment by leotaku** [comment]
So I've just read through your summary and gathered the following points:

* In its current state the dbus session cannot really be trusted to work correctly
* It might work for people that have especially configured it using your advice
* By defining custom systemd service files we may ensure that the modules work for both users with and without these configuration tweaks
  * As long as we ensure they have the same name as the upstream systemd service file, the services won't ever start twice.

Is that correct?

**Comment by pjones** [comment]
I think these are good changes.  It also doesn't start for me automatically but I haven't gotten around to fixing it yet.

**Comment by rycee** [comment]
Yep, looks good to me. I _think_ dbus will handle this correctly and not activate a new instance, if you ever end up with two running mpdris2 instances let me know 🙂

Squashed and rebased to master in 34dc4a5e03451d3e31153f9526807d75f0c61b40.

**Pull request closed without merging**
