### PR TITLE
bash-completion

### PR DESCRIPTION
**Pull request by sboosali**
fix `-A` completion

(made `bash-completion` branch)

### CODE REVIEW

**Comment by sboosali** [comment]
Issue #623

**Comment by sboosali** [comment]
this should also be tested on Bash 3 (e.g. on OSX).

could someone do that?

(I built Bash3 from source, since I couldn't find it on Nixpkgs, but it just hung when executing the completion script).

**Comment by rycee** [comment]
Looks ok to me! Unfortunately I don't have bash 3 either so can't help with testing that.

**Comment by teto** [comment]
or merge and if someone has a complaint with bash 3, well he can fix it later, bash 3 is rather old I believe.

**Comment by sboosali** [comment]
sgtm

**Comment by sboosali** [comment]
@teto Bash 3 is the latest version supported by OSX (due to a somewhat conservative licensing decision).

**Comment by rycee** [comment]
Agreed, I've rebased to master in 2211770d8b6fc22677695726499d6a09b991cfc2. I moved the completion file to the `home-manager` directory and added it to the install.

Many thanks for the contribution @sboosali!

**Pull request closed without merging**
