### PR TITLE
home-manager: respect NIX_STATE_DIR

### PR DESCRIPTION
**Pull request by veprbl**
### Checklist

- [ ] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all`.

- [ ] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md#commits) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks for the contribution! Presumably this type of system would include non-NixOS GNU/Linux distributions? If so then I guess the change also would have to include some form of configurability of the `genericLinux` module? Specifically, https://github.com/rycee/home-manager/blob/ad8b644de19aca8a7534c9695a7446b258156d06/modules/targets/generic-linux.nix#L19.

**Comment by veprbl** [comment]
@rycee I haven't tried that module, but it looks like it should work fine in single-user installations as long as `config.home.profileDirectory` is set correctly. I don't yet have a general solution in mind to extend this PR to the modules.

**Comment by rycee** [comment]
Fair enough, I've rebased to master in dc227b579d71f92e24717dac09bbe3846d5a6597. Thanks for the contribution!

**Comment by glglwty** [comment]
Reminder for those using a prefixed nix build: NIX_STATE_DIR is equivalent /nix/var/nix. I pointed it to /nix/var and messed up my entire nix store.

**Pull request closed without merging**
