### PR TITLE
fish: add plugin functionality

### LINKED ISSUE #609: Expand fish support to functions and packages?
I'm currently in the process of trying to convert my dotfiles and assorted stuff to using `home-manager` and currently I use a few custom functions and a few packages installed through `fisher`, I was curious if you'd be willing to accept PRs towards automatically installing this for `fish`? And if you have any pointers or code that can point me in the right direction if this is the case.

Thanks for `home-manager` :)

### PR DESCRIPTION
**Pull request by Jomik**
Fixes #609 
I use this setup myself here https://github.com/Jomik/dotfiles/blob/master/.config/nixpkgs/configurations/fish.nix.
However I have it in my own config, not as part of home-manager.
I am unsure how to actually test this properly, without messing with my current setup @rycee ?
Also dependent on https://github.com/NixOS/nixpkgs/pull/44601, but I have pasted that in the `let`, we have touched on that type in #518 .

My last concern is in the `plugins` folder. These would actually need to be updated - which seems to be what we want nixpkgs for - but nixpkgs has no real reason to have this sort of setup - unless we made the changes to how `pkgs.fish` is built.

### CODE REVIEW

**Comment by rycee** [comment]
Really interesting project this!

You could try creating some test cases in the [test suite](https://github.com/rycee/home-manager/blob/master/tests/default.nix). Hopefully the existing tests are sufficient to use as a base, therwise I'd be happy to assist.

About the plugin packages, I agree these are a concern. I am very reluctant to include packages in Home Manager. Perhaps having them in [NUR](https://github.com/nix-community/NUR/) would be a possibility? Then they would be accessible as regular packages so the type of the `plugins` option could have type `listOf package` instead of `selectorFunction`. See [`programs.firefox.extensions`](https://github.com/rycee/home-manager/blob/master/modules/programs/firefox.nix#L27-L41) for an example of what I mean.

I'll see if I can put together a `nur` module that allows people easily set up NUR access.

**Comment by Jomik** [comment]
That'd be awesome. I am actually wanting to setup a NUR repository for myself as well, which I need to be able to use from home-manager and with nix-shell.
I am unsure if we should use `overlays` or `nixpkgs.config.packageOverrides`? The `packageOverrides` seem to do the same as an overlay.
I suppose we could have a fish plugins nur that was loaded by default, but that requires the `selectorFunction` type.

**Comment by Jomik** [comment]
@rycee How would we go about exposing `fish-utils`?
Unless we just assume that the NUR repo will contain its own helper function. I have just made a general case one, which essentially does what [fisher](https://github.com/jorgebucaran/fisher) does.

**Comment by Jomik** [comment]
I will look into adding tests.
It remains to decide whether functions/completions specified through home-manager should be before or  after the ones in you specify in `$XDG_CONFIG_HOME/fish/{functions,completions}` in `$fish_{function,complete}_path`

**Comment by Jomik** [comment]
I have added the module to my nur-expressions for now: https://gitlab.com/Jomik/nur-expressions
I have plugins as well, in the style that you did with firefox addons.
This PR just needs some tests done..

**Comment by nyarly** [comment]
I wound up building a module based on the fisher packages. I'll see about a draft PR with that to make clear how it looks.

I see the resistance to building full packages in home-manager - should we figure out instead how to fit them into nixpkgs?

**Comment by Jomik** [comment]
This basically uses the same method that fisher and oh-my-fish uses. As in, it supports both layouts.
Fisher isn't pure, so I personally want to avoid it.

**Comment by Jomik** [comment]
Sourcing conf.d is currently broken in this PR.
Sorry for it growing stale, will come back to looking at it when I have used it a bit more myself :)

**Comment by ryanorendorff** [comment]
@Jomik Has this PR been working well for you? I am just switching my configuration over to home-manager and this seems like a much better solution that the hack I was planning to do. :-)

**Comment by Jomik** [comment]
Yes, it has been working flawlessly. I have the module on my NUR repository https://gitlab.com/Jomik/nur-expressions
And you can see how I use it here https://github.com/Jomik/dotfiles/tree/master/.config/nixpkgs

**Comment by JonathanReeve** [comment]
Please merge :smile: I would love to have this.

**Comment by Jomik** [comment]
I have, sadly, stopped using NixOS due to some issues with some software.
Is there anything missing for this PR to be merged? If need be, I can look at it - or someone else could take over.
I think @rycee would like some tests added..?

**Comment by ryanorendorff** [comment]
I could take it over if you would like. What tests were you thinking of adding?

**Comment by Jomik** [comment]
I am actually not sure how testing works for home-manager, but I guess something simple like adding a plugin, and then making sure that fish can execute a command that plugin adds.

**Comment by ryanorendorff** [comment]
I'll look into adding a few tests and try what you suggested.

Looking through the code, it seems that `buildFishPlugin` might be missing from the PR. @Jomik I saw you have defined this function in your nur-expressions repo (in `fish-utils.nix`). Would it be ok to use that definition?

**Comment by Jomik** [comment]
Definitely. This PR may be outdated compared to my NUR

**Comment by ryanorendorff** [comment]
@Jomik Would you like me to open a fresh PR or to update this one? And if you would like to update this PR, would you want to do that by either giving me write access to your fork or do you want me to add a PR to your fork (a double PR!).

**Comment by Jomik** [comment]
I've added you as collaborator on my fork, seems easiest? :)

**Comment by ryanorendorff** [comment]
Yup, sounds good!

I'll look to have something updated in the next week (famous last words).

**Comment by ryanorendorff** [comment]
I have updated the PR to handle the plugins a little differently. Instead of using `buildFishPlugin` the source paths are referenced directly and `99plugins.fish` loads the relevant parts of the source paths. This change was made because some plugins have a non-standard layout; `buildFishPlugin` attempted to make a standard layout but there is just a bit too much variation in plugin file layouts for this to work seamlessly. 

@mudrii The issue you raised (#844) is partially covered by this. Oh-my-fish handles sourcing plugin and theme files. With this PR you can directly use the plugins from oh-my-fish, as the plugins exist as separate repos that are simple to source. See an example below.

```
programs.fish.plugins = [
      {
        name = "fasd";
        src = pkgs.fetchFromGitHub {
          owner = "oh-my-fish";
          repo = "plugin-fasd";
          rev = "38a5b6b6011106092009549e52249c6d6f501fba";
          sha256 = "06v37hqy5yrv5a6ssd1p3cjd9y3hnp19d3ab7dag56fs1qmgyhbs";
        };
      }
];
```

I still need to make some tests but I have tried 5 plugins (ones I had installed using `omf`) and the plugins work as expected. The one exception was `vi-mode`, which references a python file in its repo and therefore required the python interpreter on the path. I think a decent solution to this exception is to patch the repo to call the interpreter from the nix store instead of from the users path. That particular plugin will probably also need the python file moved into somewhere else in the store so that it is possible to call it.

**Comment by ryanorendorff** [comment]
@rycee I've added tests for the functions and plugins functionality added to this PR; the functionality should be complete. Is there anything else I should do for this PR?

**Comment by aheaume** [comment]
Hello @ryanorendorff 
Thanks for maintaining this!
I merged your branch with my config, and I'm getting a bunch of
```
source: Error encountered while sourcing file “/nix/store/...-source/conf.d/*.fish”:
source: No such file or directory
```
when starting fish. Is there something I'm doing wrong, or a bug?
Let me know if I can help you with this in any way.

```
    fish = {
      enable = true;
      shellAbbrs = {...};
      plugins = [
        {
          name = "fasd";
          src = pkgs.fetchFromGitHub {
            owner = "fishgretel";
            repo = "fasd";
            rev = "a0a3c3503961b8cd36e6bec8a7ae0edbca19d105";
            sha256 = "0w618la3ggri1z2mlkkxczrr22xih6c795jgmf2634v2c1349cjq";
          };
        }
        {
          name = "fish-prompt-mono";
          src = pkgs.fetchFromGitHub {
            owner = "fishpkg";
            repo = "fish-prompt-mono";
            rev = "8ac13592d47b746a4549bcecf21549f97ad66edb";
            sha256 = "0w618la3ggri1z2mlkkxczrr22xih6c795jgmf2634v2c1349cjq";
          };
        }
        {
          name = "fzf";
          src = pkgs.fetchFromGitHub {
            owner = "jethrokuan";
            repo = "fzf";
            rev = "ac01d96fc6344ebeb48c03f2c9c0be5bf3b20f1c";
            sha256 = "1h97zh3ghcvvn2x9rj51frhhi85nf7wa072g9mm2pc6sg71ijw4k";
          };
        }
        {
          name = "plugin-bang-bang";
          src = pkgs.fetchFromGitHub {
            owner = "oh-my-fish";
            repo = "plugin-bang-bang";
            rev = "4ac4ddee91d593f7a5ffb50de60ebd85566f5a15";
            sha256 = "0w618la3ggri1z2mlkkxczrr22xih6c795jgmf2634v2c1349cjq";
          };
        }
        {
          name = "fish-ssh-agent";
          src = pkgs.fetchFromGitHub {
            owner = "danhper";
            repo = "fish-ssh-agent";
            rev = "df0de37a6cd039e27433a20195d36d156d363e40";
            sha256 = "0w618la3ggri1z2mlkkxczrr22xih6c795jgmf2634v2c1349cjq";
          };
        }
        {
          name = "pisces";
          src = pkgs.fetchFromGitHub {
            owner = "laughedelic";
            repo = "pisces";
            rev = "8d26b0852c2d4ee9983474ec157fef7d878bea1d";
            sha256 = "0kzxyyh9jhv0r4baja787n5qqzwawh4yv1i0ir6slgy1dgllnf77";
          };
        }

      ];
    };
```

```
~> tree ~/.config/fish/
~/.config/fish
├── conf.d
│  ├── plugin-fasd.fish -> /nix/store/...-home-manager-files/.config/fish/conf.d/plugin-fasd.fish
│  ├── plugin-fish-prompt-mono.fish -> /nix/store/...-home-manager-files/.config/fish/conf.d/plugin-fish-prompt-mono.fish
│  ├── plugin-fish-ssh-agent.fish -> /nix/store/...-home-manager-files/.config/fish/conf.d/plugin-fish-ssh-agent.fish
│  ├── plugin-fzf.fish -> /nix/store/...-home-manager-files/.config/fish/conf.d/plugin-fzf.fish
│  ├── plugin-pisces.fish -> /nix/store/...-home-manager-files/.config/fish/conf.d/plugin-pisces.fish
│  └── plugin-plugin-bang-bang.fish -> /nix/store/...-home-manager-files/.config/fish/conf.d/plugin-plugin-bang-bang.fish
├── config.fish -> /nix/store/...-home-manager-files/.config/fish/config.fish
└── fish_variables
```

**Comment by aheaume** [comment]
@ryanorendorff  FWIW, this seems to solve my issue

```
          # Source initialization code if it exists.
          if test -d $plugin_dir"/conf.d"
            for fishfile in (find $plugin_dir"/conf.d/" -name "*.fish")
              source $fishfile
            end
          end
```

which might suggest that `source` and globbing do not really work in the fish shell.

**Comment by ryanorendorff** [comment]
> “/nix/store/...-source/conf.d/*.fish”:

Do you know what the dots expand to? It should be a specific plugin that was causing the problem.

I'll try out your configuration and try merging in your solution to see if I can get it to work for you.

**Comment by Jomik** [comment]
Yeah, IIRC you can't use globbing when sourcing a file in fish, that's why I went with the approach I did where I wrote in each path.

**Comment by ryanorendorff** [comment]
Hmm I am a bit curious as to why the globbing worked for the plugins I had tried previously.

Either way the snippet from @aheaume should probably be used to eliminate that problem.

**Comment by aheaume** [comment]
FWIW, here is the full error and dir contents

```
source: Error encountered while sourcing file “/nix/store/7vyjb3h5l5d2z0kwvrk0fh2qlg70rlmp-source/conf.d/*.fish”:
source: No such file or directory
source: Error encountered while sourcing file “/nix/store/7vyjb3h5l5d2z0kwvrk0fh2qlg70rlmp-source/conf.d/*.fish”:
source: No such file or directory
source: Error encountered while sourcing file “/nix/store/kqcqjd1x3ppffaqyijqm8nyzlvc44iwb-source/conf.d/*.fish”:
source: No such file or directory
source: Error encountered while sourcing file “/nix/store/7vyjb3h5l5d2z0kwvrk0fh2qlg70rlmp-source/conf.d/*.fish”:
source: No such file or directory
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
```
```
~> ls /nix/store/7vyjb3h5l5d2z0kwvrk0fh2qlg70rlmp-source/conf.d/
aliases.fish  __fasd_run.fish
~> ls /nix/store/kqcqjd1x3ppffaqyijqm8nyzlvc44iwb-source/conf.d/
fzf.fish  fzf_key_bindings.fish
```

**Comment by aheaume** [comment]
If you are puzzled about the multiple errors relating to only one directory, I think I forgot to change the sha256 on some plugins (see 0w618 above). Once fixed I only get 2 errors.

**Comment by JonathanReeve** [comment]
How's this going? I'd love to see this merged.

**Comment by mbrgm** [comment]
I had to apply @aheaume fix in order to make this work. In addition, there are several additional files that should be sourced in order to make prompt, greeting etc. work.

@Jomik Should I create a patch on your branch, do you want to add me as a contributor or should I create a separate fork with my changes?

**Comment by Jomik** [comment]
> @Jomik Should I create a patch on your branch, do you want to add me as a contributor or should I create a separate fork with my changes?

I have added you as a collaborator on my fork, so feel free to update that!

**Comment by cole-h** [comment]
The real problem we had with sourcing all fish files in `conf.d` was that the wildcard was quoted, meaning it wanted to source a file named `*.fish` in `conf.d`, and not all `.fish` files in `conf.d`. Remove the quotes, and it functions as expected, no explicit looping necessary. This has been fixed with my recently-merged commits, and I believe everything should be pretty much ready to be integrated into master -- after a rebase, of course.

**Comment by rycee** [comment]
Thanks for all the work! I've merged to master in 57bd27b3e7277c9c487ac2e985bab1b9e5e591a3 with a few fixups here and there.

**Pull request closed without merging**
