### PR TITLE
update browserpass app id

### PR DESCRIPTION
**Pull request by ashkitten**
browserpass just updated to version 3, changing the app id and breaking the home-manager module. this change fixes that.

### CODE REVIEW

**Comment by t184256** [comment]
Works for me: nixos 19.03, firefox 66.0.2, extension version 3.0.9.

**Comment by rycee** [comment]
Thanks! Rebased to master in cb93316fed4f7002f332392c70b9e9844fab1a57. I guess this needs to be in the release-19.03 branch as well?

**Comment by ashkitten** [comment]
@rycee yes, and the browserpass update in nixpkgs was backported to 18.09 as well (https://github.com/NixOS/nixpkgs/pull/58639#issuecomment-478630655)

**Comment by rycee** [comment]
@ashkitten Thank you. It's in the release-19.03 and release-18.09 branches now :+1:

**Pull request closed without merging**
