### PR TITLE
Add support for switching when no previous generation has existed

### PR DESCRIPTION
**Pull request by kalbasit**
This happens only when the user does not have a profile directory yet.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks for looking into this! I'll also try investigating a bit when possible.

**Comment by kalbasit** [comment]
I believe this PR is ready, I did not remove the WIP as I haven't had a chance to retry since. Feel free to remove the WIP and merge if it looks good to you.

**Comment by kalbasit** [comment]
@rycee I finally had some time to move forward with Darwin build and I verified that this works now! This PR is now ready for your review.

**Comment by rycee** [comment]
Sorry for the very long delay. I finally had time to return to this problem and fund an alternative solution that I implemented instead. Hopefully it'll work OK for you.

**Pull request closed without merging**
