### PR TITLE
make notmuch search.exclude_tags configurable

### PR DESCRIPTION
**Pull request by NickHu**

### CODE REVIEW

**Comment by teto** [comment]
thanks

**Comment by rycee** [comment]
Not a big issue but for future reference, commit messages should be formatted according to the [contributing guidelines](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md#commits).

**Comment by rycee** [comment]
That said I really appreciate that you had a look and merged this PR @teto :+1:

**Comment by teto** [comment]
agreed sry. as I saw the PR queue going up, I thought of merging and forgot about the commit message

**Pull request merged**
