### PR TITLE
Fix nix-darwin module

### PR DESCRIPTION
**Pull request by rvolosatovs**
- #586 introduced `home-manager.useUserPackages`, which effectively disables installation of `home.packages` in current implementation - fix that (closes https://github.com/rycee/home-manager/issues/665)
- Fix assertions being ignored in `nix-darwin` module

Simply copy-pasted the solution from the NixOS module.
Not sure if something extra is to be done with the fonts.

### CODE REVIEW

**Comment by BrianHicks** [comment]
hmm, I think I spoke too soon in #665. This installs packages but does not seem to get applications. For example, I have Emacs configured through home-manager and it does not show up in `~/Applications/Nix Apps`. On the other hand, if I install it through nix-darwin's `environment.systemPackages` I get an app there (albeit not with my `init.el`)

**Comment by rvolosatovs** [comment]
Indeed, that's because `nix-darwin` only installs the packages from `environment.systemPackages` into `~/Applications`: https://github.com/LnL7/nix-darwin/blob/3ba909eb2dd3ddd893604f83048fa76cc2e47e74/modules/system/applications.nix#L17-L34

The module uses `users.users.<username>.packages`, which behaves differently(see https://github.com/LnL7/nix-darwin/pull/127).

As a matter of fact, I am able to access all the applications installed this way via Finder and Launchpad. They did take some time to appear in Launchpad though.

If you want to get the applications in your `~/Applications` directory, you may also try a hack like this:
```nix
{
	environment.systemPackages = users.users.<username>.packages;
}
```
in your `nix-darwin` config.

In any case, this has nothing to do with `home-manager` and if it is indeed a bug, it is a bug in `nix-darwin`, so please open an issue there about `users.users.<username>.packages` not working as expected.

**Comment by rvolosatovs** [comment]
@rycee

**Comment by rycee** [comment]
Hey! I'm travelling at the moment but I'll have a look on Saturday 😃

On May 16, 2019 9:51:18 AM GMT+02:00, Roman Volosatovs <notifications@github.com> wrote:
>@rycee
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rycee/home-manager/pull/702#issuecomment-492958978

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rycee** [comment]
Thanks! Rebased to master in 1480a6ca1429468016d61165c33d49866743981b.

**Pull request closed without merging**
