### PR TITLE
home-manager: Add generation expiration command.

### PR DESCRIPTION
**Pull request by alunduil**
This adds a rudimentary generation expiration command to the repertoire of home-manager.  This way we can remove generations older than a specified absolute or relative date independently of the system wide garbage collection.

### CODE REVIEW

**Comment by rycee** [comment]
Thanks! This is a nice idea :+1: I've been traveling but will have a closer look within the next few days.

**Comment by alunduil** [comment]
That sounds perfect!  Let me know if you can see any cleaner way to do the date math involved, but the only thing I might change is the variable name from COUNT to SKIP_GENERATIONS or something.  I haven't thought of a better name for that variable.

**Comment by rycee** [comment]
Played around with this and came up with this alternative implementation. I'll test is more next time I have time to look at it.
```bash
function doExpireGenerations() {
    local profileDir="/nix/var/nix/profiles/per-user/$USER"

    local generations
    generations="$(\
        find "$profileDir" -name 'home-manager-*-link' -not -newermt "$1" \
        | sed 's/^.*-\([0-9]*\)-link$/\1/' \
    )"

    if [[ -n $generations ]]; then
        # shellcheck disable=2086
        doRmGenerations $generations
    elif [[ -v VERBOSE ]]; then
        echo "No generations to expire"
    fi
}
```

**Comment by alunduil** [comment]
@rycee that looks much cleaner.  I'll incorporate that so we can get this merged.

**Comment by alunduil** [comment]
I can confirm this solution works as I expect on my system without any issues.

**Comment by rycee** [comment]
Squashed and rebased to master in 3b9b897af36c31ee67e848e6583598e5cb655b67 with some minor cleanups.

**Pull request closed without merging**
