### PR TITLE
add reverse sort options to neomutt

### LINKED ISSUE #1035: neomutt: support reverse sorting methods
Per the neomutt [documentation](https://neomutt.org/guide/reference.html#3-388-%C2%A0sort):

> You may optionally use the "reverse-" prefix to specify reverse sorting order.
Example:
`set sort=reverse-date-sent`

I figure it's best to not hard-code the reverse sorting options, but maybe map over the existing enum and include `reverse-` options?

Or is this not best practice when it comes to defining type defaults and such?

cc @teto

### PR DESCRIPTION
**Pull request by evanjs**
Closes #1035 

This seems to work great on my system, but please do let me know if there is anything that can be improved.

@teto

### CODE REVIEW

**Comment by rycee** [comment]
Thanks for the PR! You'll have to run the `format` script in the project root to fix the build error. Also change the commit message to

> neomutt: add reverse sort options

**Comment by evanjs** [comment]
Derp.  You'd think I'd be used to this commit naming scheme by now.
And I figured as much re format.  Thanks!

**Comment by teto** [comment]
This looks good. One comment on my inital PR rather than yours is that in fact almost all neomutt settings should go to account-neomutt.nix since mutt doesnt distinguish between per account and global settings thus each account should be able to change everything; unlike what is now possible.

**Comment by evanjs** [comment]
> This looks good. One comment on my inital PR rather than yours is that in fact almost all neomutt settings should go to account-neomutt.nix since mutt doesnt distinguish between per account and global settings thus each account should be able to change everything; unlike what is now possible.

Sure, this sounds good. We can probably do this altogether in a separate PR.

**Pull request merged**
