### PR TITLE
oh-my-zsh: set dir cache to "$HOME/.cache/oh-my-zsh"

### PR DESCRIPTION
**Pull request by uvNikita**
This will fix this errors appearing on completion:
```
_store_cache:46: read-only file system: ...
```
More information here https://github.com/NixOS/nixpkgs/issues/21443.

### CODE REVIEW

**Comment by rycee** [comment]
This seems like a fix that belongs in Nixpkgs. I made a comment in the issue you mentioned. If it doesn't get fixed in Nixpkgs within the next few days I'd be happy to merge this.

**Comment by uvNikita** [comment]
Sounds good, thank you.

**Comment by rycee** [comment]
I suspect it'll take a while to happen in Nixpkgs so please update this PR so that it respects `$XDG_CACHE_HOME` and I'll merge it into Home Manager :-)

**Comment by uvNikita** [comment]
Done :)

**Comment by rycee** [comment]
I shortened the commit message slightly and rebased into master in 85a71a3923cdf1b482c8a1d5b617e017dbefc974. Thanks!

**Pull request closed without merging**
