### PR TITLE
i3: Update default i3 key bindings

### PR DESCRIPTION
**Pull request by Enzime**
Update to match the default i3 key bindings

https://github.com/i3/i3/blob/master/etc/config

### CODE REVIEW

**Comment by rycee** [comment]
@uvNikita Mind having a look when you have the time?

@Enzime Changing these values break the test suite, you can see this from the failed Travis-CI job. We would be unable to merge this until the tests have been fixed.

**Comment by uvNikita** [comment]
Looks good to me, thanks for the PR!

@Enzime do you mind to update this file with expected config output to fix failing test? https://github.com/rycee/home-manager/blob/master/tests/modules/services/window-managers/i3-keybindings-expected.conf

**Comment by rycee** [comment]
… to run the test locally run
```console
$ nix-shell tests -A run.i3-keybindings
```
when in the HM project directory.

**Comment by Enzime** [comment]
Fixed :)

**Comment by rycee** [comment]
Thanks! Squashed and rebased to master in df4db5063238f391352b2d334ac3e72f6fb7ade4.

**Pull request closed without merging**
