### PR TITLE
services/dunst: add `dunstrc` option

### PR DESCRIPTION
**Pull request by Ma27**
I'm currently trying out home-manager on my personal setup and I have an
existing `dunstrc` in `~/.config`.

Rather than rewriting the config as a Nix attribute set I'd prefer to
simply include the config file.

### CODE REVIEW

**Comment by Ma27** [comment]
Please note that the diff looks rather big now as I removed the `mkMerge` expression (and thus the now obsolete indent).

**Comment by teto** [comment]
mbsync (and other HM software) distinguishes between programs.mbsync and services.mbsync. This seems a similar approach would work for you as you want the service without the config generation.

Alternatively I would prefer an `extraConfig` setting which you can load from your dunstrc.

**Comment by Ma27** [comment]
> mbsync (and other HM software) distinguishes between programs.mbsync and services.mbsync. This seems a similar approach would work for you as you want the service without the config generation
.
I actually want to use the dunst *service*, but I don't need the config generation since I have an existing config file.

> Alternatively I would prefer an `extraConfig` setting which you can load from your dunstrc

.That's a reasonable idea though, what does @rycee think about this? :)

**Comment by Ma27** [comment]
After playing a bit more around with home-manager I guess that I'm not a big fan of `extraConfig`.

I.e. in the `i3wm` module `extraConfig` means that all the config lines are merged together with some defaults generated by the module. This broke my desktop in that case since my i3 config is rather complex and incompatible with the generated defaults. In the end I explicitly want to be able to deploy existing config files with Nix reproducibly into my home directory.

Thus I think it's better to provide a `dunstrc` option here and keep it mutually exclusive to `settings`.

**Comment by teto** [comment]
can't you use something like mkForce or mkOverride to get rid of the defaults ? otherwise there is little incentive to use the HM module, just symlink the files.

**Comment by Ma27** [comment]
> otherwise there is little incentive to use the HM module

I still need the service :)

But in the end you're right, let's close this and use the power of NixOS's module system rather than messing around here.

**Pull request closed without merging**
