### PR TITLE
Support conditional module loading

### PR DESCRIPTION
**Pull request by rycee**
In particular, mark Linux specific modules as such.

### CODE REVIEW

**Comment by jwiegley** [comment]
@rycee Sure. It builds fine here, I'll let you know if there are any problems.

**Comment by league** [comment]
@rycee Seems to evaluate fine for me too, and `home-manager news` doesn't list Linux-specific stuff like xsession.

**Comment by league** [comment]
@rycee: Ah, I should have run `home-manager switch` again to ensure it was bootstrapping correctly. I encountered a reference to `systemd.user = ...` that wasn't behind a `mkIf` or similar. So that's something I got away with previously but flagged an error now.

**Comment by rycee** [comment]
@league Ah, yeah. That is a bit unfortunate, I wonder how many mac users who are reusing their Linux config?

In any case, I think it is not enough to do something like
```nix
{
  some.option = "foo";

  xresources = mkIf (pkgs.hostPlatform.isLinux && cfg.enable) {
    # …
  };
}
```
it would have to be
```nix
mkMerge [
  (mkIf (pkgs.hostPlatform.isLinux && cfg.enable) {
    xresources = {
      # …
    };
  })

  {
    some.option = "foo";
  }
]
```
Which is a bit unfortunate. It is probably nicest to put the Linux specific stuff in a separate file that is conditionally imported into your configuration. Maybe something like
```nix
imports = [ ./foo.nix ./bar.nix ]
  ++ optional pkgs.hostPlatform.isLinux ./linux-conf.nix;
```
?

**Comment by league** [comment]
@rycee Yeah, that would require some refactoring of what I have now. I recently built up a more extensive configuration for NixOS and other Linux machines, that uses imports and enable flags more thoroughly, and also the `home-manager.users.NAME` module, so all user profiles are updated with a single `nixos-rebuild`. My Mac config links into that, but just doesn't enable very much of it.

It's not a problem for me personally to partition those imports based on the platform, although I'm not in a rush to do it either. If you merged this I'd probably pin a version of H-M before the change until I'm ready to do that refactoring. But it's definitely not so onerous that I'd maintain a separate branch to avoid it.

But I guess this experience answers the question, that it *can be* a breaking change for some of us.

**Comment by rycee** [comment]
@league Thanks for the good explanation!

I think I'll sit on this for a while and try to figure out a more smooth way to introduce this change. I guess the ideal would be to have something like `stateVersion <= "18.09" || hostPlatform.isLinux` as condition but the state version is defined within a module itself so it is a bit tricky to access here. I shall retire to my cave to ponder 🙂

**Comment by rycee** [comment]
I realized that the condition still might be useful for future modules so I've cleaned up the PR to allow all modules even on mac but still let us use conditional inclusion for future modules.

I'll still have to figure out a way to have the old modules that are Linux only, though. But I'll merge and close this for now and make a new PR when I've come up with something.

Many thanks @jwiegley and @league for trying this out!

**Pull request merged**
