### PR TITLE
Add experimental plugin support

### PR DESCRIPTION
**Pull request by dustinlacewell**
Experimental Plugin Support
=====================

* Set `$HOME_MANAGER_PLUGINS` to the absolute path of a Nix expression.
* Home Manager merges plugins into `pkgs`
* Home Manager also loads plugin option declaration modules

Example plugins.nix
--------------------

The following shows what the plugin expression ought to look like. Just an attrset with each downloaded plugin. In addition to `fetchFromGitHub` any other fetching mechanism also works.

```nix
with import <nixpkgs> {};

{
  org-build = import (fetchFromGitHub {
    owner = "dustinlacewell";
    repo = "nix-hm-org-build";
    rev = "d552b462b25d680981dc5a0d6cdc27a364cce8fd";
    sha256 = "16qs3dnpyx4z90m15g9kk30irxykv2c7i1nxi4a9ssc3w4i9y70d";
  });

  org-export = import (fetchFromGitHub {
    owner = "dustinlacewell";
    repo = "nix-hm-org-export";
    rev = "cbeb9b86e843cf400c95bcbe7a062fcfc63cec73";
    sha256 = "06bsmw95d3fqqqwbgvmpkvd94hmjhzv27bzmjc0nyfv4xdxcg53a";
  });
}
```

Example plugin source
----------------------

A plugin is a _function_ that takes `{ pkgs, lib }` and returns an _attrset_. The attrset is made available in your own modules as `pkgs.pluginName`.  

One attribute, `module` is special and defines the plugin module. The module attribute should be assigned a module function, module attrset or empty attrset.

This example plugin provides a library function `pkgs.org-build.build` which compiles an Orgmode file to Elisp. It also declares an Option `plugins.org-build`. The plugin utilizes its own `build` function to handle the Option's behavior. The full plugin can be found here: https://github.com/dustinlacewell/nix-hm-org-build/

```nix
{ pkgs, lib }:

with lib;
with builtins;


rec {

  # export a library function
  build = { source }: let
    env = { buildInputs = [ pkgs.emacs ]; };
    script = ''
      ln -s "${source}" ./init.org;
      emacs -Q --script "${./org-build.el}" -f make-init-el;
      cp ./init.el $out;
    '';
  in pkgs.runCommand "org-build" env script;

  # export a module to declare options
  module = {config, pkgs, lib, ...}:
  let
    cfg = config.plugins.org-build;
  in {
    options.plugins.org-build = {
      enable = mkEnableOption "Build init.el from Orgmode file";
      source = mkOption {
        type = types.path;
        description = ''
          The source orgfile to build as init.el
        '';
      };
    };

    config = mkIf cfg.enable {
      home.file.".emacs.d/init.el".source = build { source=cfg.source; };
    };
  };
}
```

Example use
------------

Here is my actual personal expression for installing emacs and rendering `init.org` -> `init.el` which uses the `org-build` plugin.

```nix
{ pkgs, ... }:

let
  # call a plugin library function
  result = pkgs.org-export.export {
    source = ./init.org;
    user = "dustinlacewell";
    repo = "emacs.d";
    token = builtins.getEnv "EMACS_D_GITHUB_TOKEN";
  };

in {
  programs.emacs = { enable = true; };
  # utilize a plugin declared option
  plugins.org-build = { enable = true; source = ./init.org; };
}
```

### CODE REVIEW

**Comment by rycee** [comment]
Thanks for the contribution! I like the idea of plugins and similar methods of making the modules extensible.

Right now I'm suspecting that everything that this form of plugins, at least in its current form, can do also could be accomplished using `imports`. I'll have to ponder for a while to see whether my suspicion actually is true. If `imports` is sufficiently powerful then my inclination would be not to merge this and instead suggest to use plain modules and instead do something like
```nix
{
  import = [
    (fetchFromGitHub {
      owner = "dustinlacewell";
      repo = "nix-hm-org-build";
      rev = "d552b462b25d680981dc5a0d6cdc27a364cce8fd";
      sha256 = "16qs3dnpyx4z90m15g9kk30irxykv2c7i1nxi4a9ssc3w4i9y70d";
    })
  ];

  org-build =  { enable = true; source = ./init.org; };
}
```

**Comment by dustinlacewell-wk** [comment]
I don't think so. Module imports can only declare and define new options. Overlays can only make new pkgs available. Plugins are able to make new pkgs library code available in addition to declaring and defining options.

**Comment by dustinlacewell** [comment]
I don't think so. Module imports can only declare and define new options. Overlays can only make new pkgs available. Plugins are able to make new pkgs library code available in addition to declaring and defining options.

**Comment by Infinisil** [comment]
I think it would be better to add a `nixpkgs.overlays` option (like in the nixos module), which can then provide additional attributes to `pkgs` (including adding functions to `lib`). Then all of this would be possible through importing modules (which can then again set the `nixpkgs.overlays` option to provide more packages). This will then be consistent nixos modules.

**Comment by rycee** [comment]
@dustinlacewell The nixpkgs module is in master now. If it suffices for your purposes then I suggest to close this PR. If not then please let me know which functionality is missing.

**Comment by rycee** [comment]
I believe all aspects of plugins are now supported so I'll close this. Many thanks for highlighting this missing part of HM!

**Pull request closed without merging**
