### PR TITLE
FAQ: Add instructions on targeting multiple machines

### PR DESCRIPTION
**Pull request by bsima**
Content taken from https://github.com/rycee/home-manager/issues/394#issuecomment-422958338

### CODE REVIEW

**Comment by teto** [comment]
I would rather see this kind of "tip" into the wiki https://github.com/rycee/home-manager/wiki. Hopefully home-manager gets integrated in nix/nixos.

**Comment by sboosali** [comment]
as a non-nixos user of home-manager, yes, I'd like to know the "official
recommendation". and have it on the wiki.

**Comment by bsima** [comment]
I would add this to the wiki, but it seems I don't have access to do so.

**Comment by rycee** [comment]
Thanks! I've edited the text a bit and rebased to master in b08e6221e0a227469e992bf4b302edebeedba006.

About the wiki I don't have any strong opinion but perhaps the [NixOS wiki](https://nixos.wiki/) is more suitable than the GitHub one? Somebody already created a [page for Home Manager](https://nixos.wiki/wiki/Home_Manager).

**Pull request closed without merging**
